services:
  postgres:
    extends:
      file: compose.services.yml
      service: postgres

  backend:
    extends:
      file: compose.services.yml
      service: backend
    build:
      context: ../backend

  notification-worker:
    extends:
      file: compose.services.yml
      service: notification-worker
    build:
      context: ../backend

  github-worker:
    extends:
      file: compose.services.yml
      service: github-worker
    build:
      context: ../backend

  frontend:
    extends:
      file: compose.services.yml
      service: frontend
    build:
      context: ../frontend
      args:
        NODE_MAJOR: ${FRONTEND_NODE_MAJOR:-24}

volumes:
  pgdata:
