import { useState, type FormEvent } from "react";
import { useApiResource } from "../lib/use-api-resource";
import { ErrorNotice, Pagination } from "../components/feedback";

type Event = { id: string; actor: string; action: string; object_type: string; object_id: string | null; details: Record<string, unknown>; created_at: string };
const limit = 50;
export default function AuditPage() {
  const [offset, setOffset] = useState(0); const [draft, setDraft] = useState({ actor: "", action: "", object_type: "" }); const [filters, setFilters] = useState(draft);
  const { data, error, loading, reload } = useApiResource<{ count: number; results: Event[] }>("/audit-events", { ...filters, offset, limit });
  function apply(event: FormEvent) { event.preventDefault(); setOffset(0); setFilters({ ...draft }); }
  return <div className="space-y-5"><header><h1 className="text-3xl font-semibold">Audit log</h1><p className="mt-2 text-sm text-gray-600 dark:text-gray-300">Review account, access, workflow, integration and policy changes recorded by the server.</p></header><form className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4 dark:border-gray-700 dark:bg-gray-800" onSubmit={apply}>{(["actor", "action", "object_type"] as const).map(name => <label className="grid gap-1 text-sm" key={name}>{name.replace("_", " ")}<input className="input" maxLength={100} value={draft[name]} onChange={event => setDraft({ ...draft, [name]: event.target.value })} /></label>)}<button className="button-primary">Apply filters</button><button type="button" className="button-secondary" disabled={loading} onClick={reload}>Refresh</button></form><ErrorNotice message={error} retry={reload} />{loading && <p role="status">Loading audit events…</p>}{data && <>{!data.results.length ? <p>No audit events match these filters.</p> : <div className="overflow-x-auto rounded-xl border bg-white dark:border-gray-700 dark:bg-gray-800"><table className="min-w-full text-sm"><caption className="sr-only">Audit events</caption><thead><tr className="text-left">{["Time", "Actor", "Action", "Object", "Details"].map(label => <th key={label} scope="col" className="p-3">{label}</th>)}</tr></thead><tbody>{data.results.map(row => <tr key={row.id} className="border-t align-top dark:border-gray-700"><td className="whitespace-nowrap p-3">{new Date(row.created_at).toLocaleString()}</td><td className="p-3">{row.actor}</td><td className="p-3 font-medium">{row.action}</td><td className="p-3"><div>{row.object_type}</div>{row.object_id && <div className="max-w-xs break-all font-mono text-xs text-gray-500">{row.object_id}</div>}</td><td className="p-3"><details><summary className="cursor-pointer">View fields</summary><pre className="mt-2 max-w-lg overflow-auto whitespace-pre-wrap break-words rounded bg-gray-50 p-2 text-xs dark:bg-gray-900">{JSON.stringify(row.details, null, 2)}</pre></details></td></tr>)}</tbody></table></div>}<Pagination count={data.count} offset={offset} limit={limit} loading={loading} onPage={setOffset} /></>}</div>;
}
