import Link from "next/link";
import { useState } from "react";
import { useApiResource } from "../lib/use-api-resource";
import { ErrorNotice, Pagination } from "../components/feedback";

type Finding = { id: string; project: string; title: string; asset: string; severity: string; status: string; priority_score: number; remediation_due_at: string | null; last_seen: string };
const limit = 50;
export default function MyQueuePage() {
  const [offset, setOffset] = useState(0);
  const { data, error, loading, reload } = useApiResource<{ count: number; overdue: number; results: Finding[] }>("/my-queue", { offset, limit });
  return <div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-indigo-600 dark:text-indigo-400">Personal worklist</p><h1 className="mt-1 text-3xl font-semibold">My queue</h1><p className="mt-2 text-sm text-gray-600 dark:text-gray-300">Active findings assigned to your dashboard username, ordered by priority and deadline.</p></div><button className="button-secondary" disabled={loading} onClick={reload}>Refresh</button></header><ErrorNotice message={error} retry={reload} />{loading && <p role="status">Loading your queue…</p>}{data && <><section className="grid max-w-md grid-cols-2 gap-3" aria-label="Queue summary"><Metric label="Assigned" value={data.count} /><Metric label="Overdue" value={data.overdue} danger={data.overdue > 0} /></section>{!data.results.length ? <p className="rounded-xl border p-6 dark:border-gray-700">Nothing is currently assigned to you.</p> : <div className="overflow-x-auto rounded-xl border bg-white dark:border-gray-700 dark:bg-gray-800"><table className="min-w-full text-sm"><caption className="sr-only">Findings assigned to me</caption><thead><tr className="text-left">{["Priority", "Severity", "Finding", "Project / asset", "Status", "Deadline", "Last seen"].map(label => <th key={label} className="p-3" scope="col">{label}</th>)}</tr></thead><tbody>{data.results.map(row => <tr key={row.id} className="border-t dark:border-gray-700"><td className="p-3 font-bold">{row.priority_score}</td><td className="p-3">{row.severity}</td><td className="p-3"><Link className="text-indigo-600 hover:underline dark:text-indigo-400" href={`/findings/${row.id}`}>{row.title}</Link></td><td className="p-3"><div className="font-medium">{row.project || "No project"}</div><div className="break-all text-xs">{row.asset}</div></td><td className="p-3">{row.status.replaceAll("_", " ")}</td><td className="whitespace-nowrap p-3">{row.remediation_due_at ? new Date(row.remediation_due_at).toLocaleDateString() : "Untracked"}</td><td className="whitespace-nowrap p-3">{new Date(row.last_seen).toLocaleDateString()}</td></tr>)}</tbody></table></div>}<Pagination count={data.count} offset={offset} limit={limit} loading={loading} onPage={setOffset} /></>}</div>;
}
function Metric({ label, value, danger = false }: { label: string; value: number; danger?: boolean }) { return <div className="rounded-xl border bg-white p-4 dark:border-gray-700 dark:bg-gray-800"><div className="text-xs text-gray-500">{label}</div><div className={`mt-1 text-2xl font-bold ${danger ? "text-red-700 dark:text-red-300" : ""}`}>{value}</div></div>; }
